### ISSUE TITLE
Tests fail with -Duselongdouble

### ISSUE THREAD

**Issue by eserte** [net-amqp-rabbitmq/net-amqp-rabbitmq#68] opened 2015-09-30 16:34 UTC
Again sample test report http://www.cpantesters.org/cpan/report/11907dc8-676a-11e5-848a-573096b0373b : t/023_numeric_header_fields.t fails, probably because caused by a perl built with long double support.

**Comment by markwellis** [comment] 2015-09-30 16:36
is this the same as #11?

**Comment by eserte** [comment] 2015-09-30 16:43
Yes. But with a slightly better issue title ;-)

**Comment by markwellis** [comment] 2015-10-01 09:48
I'm closing this as a duplicate of #11, but stealing the better title for it :)

**Closed by markwellis** 2015-10-01 09:48 UTC
