### ISSUE TITLE
Access to the underlying socket

### ISSUE THREAD

**Issue by DavsX** [net-amqp-rabbitmq/net-amqp-rabbitmq#49] opened 2015-03-27 15:20 UTC
Hi!
Is there a way to access the raw socket via Net::AMQP::RabbitMQ? I'd like to use something like IO::Poll on it. My process has more sockets to listen to, and if they are blocked by IO::Poll, then new messages on the AMQP handle are not checked.

**Comment by manchicken** [comment] 2015-03-27 15:45
Well, we do get the file descriptor, kinda, but the problem is that the
file descriptor could be plaintext or could be SSL. Are you just wanting to
catch interrupts when traffic comes through, or are you wanting to do
something with that traffic?

**Comment by DavsX** [comment] 2015-03-27 16:26
The existing logic polls over a few UNIX/INET sockets (blocking until there is some event), and after handles the input/output traffic (syswrite/sysread). I'd like to include the AMQP socket in this poll as well.

**Comment by manchicken** [comment] 2015-03-27 17:45
Okay, at the moment consume() followed by recv() does most of what you’re
describing, but it does not yet expose the file descriptor for you to poll
yourself.
​

**Comment by DavsX** [comment] 2015-03-27 21:28
Is it something you would consider adding as a feature? :)

**Comment by manchicken** [comment] 2015-03-28 02:42
Yeah, I just worry about the existing backlog.

**Comment by markwellis** [comment] 2015-09-30 11:46
i fogot i merged this. I've just released version 1.000000 to fix #63, so this will be available as soon as that shows up on cpan. it's totally undocumented though, it's not even in the chagelog

**Closed by markwellis** 2015-09-30 11:46 UTC
Labels: hackathon
