### ISSUE TITLE
SSL test fails on Debian

### ISSUE THREAD

**Issue by eserte** [net-amqp-rabbitmq/net-amqp-rabbitmq#186] opened 2020-02-23 13:54 UTC
On newer Debian systems (buster (current stable) and bullseye) the t/030_ssl.t test fails:
```
#   Failed test 'connected'
#   at t/030_ssl.t line 30.

#   Failed test 'channel_open'
#   at t/030_ssl.t line 31.

#   Failed test 'exchange declare'
#   at t/030_ssl.t line 33.

#   Failed test 'queue declare'
#   at t/030_ssl.t line 34.

#   Failed test 'queue bind'
#   at t/030_ssl.t line 35.

#   Failed test 'drain queue'
#   at t/030_ssl.t line 36.

#   Failed test 'consume'
#   at t/030_ssl.t line 38.

#   Failed test 'publish'
#   at t/030_ssl.t line 39.

#   Failed test 'payload matches'
#   at t/030_ssl.t line 53.
#     Structures begin differing at:
#          $got = undef
#     $expected = HASH(0x560c192ed0a8)
# Looks like you failed 9 tests of 9.
t/030_ssl.t ............................ 
Dubious, test returned 9 (wstat 2304, 0x900)
Failed 9/9 subtests 
```

Looking with strace into the script it seems that a connection is not even attempted --- it seems to fail earlier:
```
15476 13:41:51.180569 write(5, "# ssl mode\n", 11) = 11 <0.000027>
15476 13:41:51.180875 openat(AT_FDCWD, "/usr/lib/ssl/openssl.cnf", O_RDONLY) = 3 <0.000028>
15476 13:41:51.181005 futex(0x7fda4840c818, FUTEX_WAKE_PRIVATE, 2147483647) = 0 <0.000023>
15476 13:41:51.181074 futex(0x7fda4840c80c, FUTEX_WAKE_PRIVATE, 2147483647) = 0 <0.000017>
15476 13:41:51.181136 futex(0x7fda4840c804, FUTEX_WAKE_PRIVATE, 2147483647) = 0 <0.000017>
15476 13:41:51.181198 futex(0x7fda4840c6c4, FUTEX_WAKE_PRIVATE, 2147483647) = 0 <0.000017>
15476 13:41:51.181290 fstat(3, {st_mode=S_IFREG|0644, st_size=11118, ...}) = 0 <0.000022>
15476 13:41:51.181368 read(3, "#\n# OpenSSL example configuration file.\n# This is mostly being used for generation of certificate requests.\n#\n\n# Note that you can include other files from the main configuration\n# file using the .include directive.\n#.include filename\n\n# This definition stops the following lines choking if HOME isn't\n# defined.\nHOME\t\t\t= .\n\n# Extra OBJECT IDENTIFIER info:\n#oid_file\t\t= $ENV::HOME/.oid\noid_section\t\t= new_oids\n\n# System default\nopenssl_conf = default_conf\n\n# To use this configuration file with the \"-extfile\" op"..., 4096) = 4096 <0.000023>
15476 13:41:51.181467 brk(0x56505e6d2000) = 0x56505e6d2000 <0.000028>
15476 13:41:51.181553 read(3, "F8Strings).\n# MASK:XXXX a literal mask value.\n# WARNING: ancient versions of Netscape crash on BMPStrings or UTF8Strings.\nstring_mask = utf8only\n\n# req_extensions = v3_req # The extensions to add to a certificate request\n\n[ req_distinguished_name ]\ncountryName\t\t\t= Country Name (2 letter code)\ncountryName_default\t\t= AU\ncountryName_min\t\t\t= 2\ncountryName_max\t\t\t= 2\n\nstateOrProvinceName\t\t= State or Province Name (full name)\nstateOrProvinceName_default\t= Some-State\n\nlocalityName\t\t\t= Locality Name (eg, city)\n\n0.or"..., 4096) = 4096 <0.000023>
15476 13:41:51.181659 read(3, "icConstraints=CA:FALSE\n\n# Here are some examples of the usage of nsCertType. If it is omitted\n# the certificate can be used for anything *except* object signing.\n\n# This is OK for an SSL server.\n# nsCertType\t\t\t= server\n\n# For an object signing certificate this would be used.\n# nsCertType = objsign\n\n# For normal client use this is typical\n# nsCertType = client, email\n\n# and for everything including object signing:\n# nsCertType = client, email, objsign\n\n# This is typical in keyUsage for a client certificate.\n"..., 4096) = 2926 <0.000023>
15476 13:41:51.181757 read(3, "", 4096) = 0 <0.000023>
15476 13:41:51.181830 close(3)          = 0 <0.000022>
15476 13:41:51.181949 futex(0x7fda4840c65c, FUTEX_WAKE_PRIVATE, 2147483647) = 0 <0.000017>
15476 13:41:51.182012 futex(0x7fda4840c650, FUTEX_WAKE_PRIVATE, 2147483647) = 0 <0.000017>
15476 13:41:51.182729 futex(0x7fda4840c7fc, FUTEX_WAKE_PRIVATE, 2147483647) = 0 <0.000022>
15476 13:41:51.182831 openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3 <0.000025>
15476 13:41:51.182906 fstat(3, {st_mode=S_IFREG|0644, st_size=103644, ...}) = 0 <0.000022>
15476 13:41:51.182981 mmap(NULL, 103644, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fda480ad000 <0.000024>
15476 13:41:51.183051 close(3)          = 0 <0.000017>
15476 13:41:51.183147 openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libssl_conf.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000025>
15476 13:41:51.183223 openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/libssl_conf.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000024>
15476 13:41:51.183297 openat(AT_FDCWD, "/lib/tls/haswell/x86_64/libssl_conf.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000026>
15476 13:41:51.183376 stat("/lib/tls/haswell/x86_64", 0x7ffcf26c57b0) = -1 ENOENT (No such file or directory) <0.000017>
15476 13:41:51.183445 openat(AT_FDCWD, "/lib/tls/haswell/libssl_conf.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000023>
15476 13:41:51.183519 stat("/lib/tls/haswell", 0x7ffcf26c57b0) = -1 ENOENT (No such file or directory) <0.000022>
15476 13:41:51.183591 openat(AT_FDCWD, "/lib/tls/x86_64/libssl_conf.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000022>
15476 13:41:51.183664 stat("/lib/tls/x86_64", 0x7ffcf26c57b0) = -1 ENOENT (No such file or directory) <0.000017>
15476 13:41:51.183732 openat(AT_FDCWD, "/lib/tls/libssl_conf.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000023>
15476 13:41:51.183806 stat("/lib/tls", 0x7ffcf26c57b0) = -1 ENOENT (No such file or directory) <0.000023>
15476 13:41:51.183879 openat(AT_FDCWD, "/lib/haswell/x86_64/libssl_conf.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000023>
15476 13:41:51.183952 stat("/lib/haswell/x86_64", 0x7ffcf26c57b0) = -1 ENOENT (No such file or directory) <0.000017>
15476 13:41:51.184019 openat(AT_FDCWD, "/lib/haswell/libssl_conf.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000023>
15476 13:41:51.184093 stat("/lib/haswell", 0x7ffcf26c57b0) = -1 ENOENT (No such file or directory) <0.000023>
15476 13:41:51.184166 openat(AT_FDCWD, "/lib/x86_64/libssl_conf.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000024>
15476 13:41:51.184242 stat("/lib/x86_64", 0x7ffcf26c57b0) = -1 ENOENT (No such file or directory) <0.000023>
15476 13:41:51.184315 openat(AT_FDCWD, "/lib/libssl_conf.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000023>
15476 13:41:51.184389 stat("/lib", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0 <0.000025>
15476 13:41:51.184468 openat(AT_FDCWD, "/usr/lib/tls/haswell/x86_64/libssl_conf.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000024>
15476 13:41:51.184541 stat("/usr/lib/tls/haswell/x86_64", 0x7ffcf26c57b0) = -1 ENOENT (No such file or directory) <0.000022>
15476 13:41:51.184614 openat(AT_FDCWD, "/usr/lib/tls/haswell/libssl_conf.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000022>
15476 13:41:51.184687 stat("/usr/lib/tls/haswell", 0x7ffcf26c57b0) = -1 ENOENT (No such file or directory) <0.000023>
15476 13:41:51.184760 openat(AT_FDCWD, "/usr/lib/tls/x86_64/libssl_conf.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000023>
15476 13:41:51.184833 stat("/usr/lib/tls/x86_64", 0x7ffcf26c57b0) = -1 ENOENT (No such file or directory) <0.000022>
15476 13:41:51.184906 openat(AT_FDCWD, "/usr/lib/tls/libssl_conf.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000023>
15476 13:41:51.184979 stat("/usr/lib/tls", 0x7ffcf26c57b0) = -1 ENOENT (No such file or directory) <0.000022>
15476 13:41:51.185052 openat(AT_FDCWD, "/usr/lib/haswell/x86_64/libssl_conf.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000023>
15476 13:41:51.185126 stat("/usr/lib/haswell/x86_64", 0x7ffcf26c57b0) = -1 ENOENT (No such file or directory) <0.000023>
15476 13:41:51.185199 openat(AT_FDCWD, "/usr/lib/haswell/libssl_conf.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000023>
15476 13:41:51.185273 stat("/usr/lib/haswell", 0x7ffcf26c57b0) = -1 ENOENT (No such file or directory) <0.000022>
15476 13:41:51.185347 openat(AT_FDCWD, "/usr/lib/x86_64/libssl_conf.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000022>
15476 13:41:51.185420 stat("/usr/lib/x86_64", 0x7ffcf26c57b0) = -1 ENOENT (No such file or directory) <0.000022>
15476 13:41:51.185493 openat(AT_FDCWD, "/usr/lib/libssl_conf.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000023>
15476 13:41:51.185567 stat("/usr/lib", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0 <0.000023>
15476 13:41:51.185646 munmap(0x7fda480ad000, 103644) = 0 <0.000073>
15476 13:41:51.185841 getpid()          = 15476 <0.000022>
15476 13:41:51.185911 getpid()          = 15476 <0.000017>
15476 13:41:51.185992 getpid()          = 15476 <0.000022>
15476 13:41:51.186096 write(5, "# error creating SSL socket at /home/cpansand/.cpan/build/2020022311/Net-AMQP-RabbitMQ-2.40005-0/t/lib/NAR/Helper.pm line 141.\n", 127) = 127 <0.000026>
```

I don't see this problem on other of my Linux smokers (Ubuntu, Fedora, CentOS).

**Comment by eserte** [comment] 2020-02-23 13:58
> I don't see this problem on other of my Linux smokers (Ubuntu, Fedora, CentOS).

Correction: it also fails on CentOS 8. CentOS 6 & 7 are OK.

**Comment by manchicken** [comment] 2020-02-23 14:01
Is there a correlation in the OpenSSL version?

~ Michael D. Stemle, Jr.

**Comment by eserte** [comment] 2020-02-23 14:17
Another correction: Fedora 31 is also affected.

So here's the list of os/distro+version and output of  `openssl version`:
```
FAIL:
debian:10:    OpenSSL 1.1.1d  10 Sep 2019
debian:11:    OpenSSL 1.1.1d  10 Sep 2019
fedora:31:    OpenSSL 1.1.1d FIPS  10 Sep 2019
centos:8:     OpenSSL 1.1.1c FIPS  28 May 2019

PASS:
freebsd:12:   OpenSSL 1.1.1d-freebsd  10 Sep 2019
freebsd:13:   OpenSSL 1.1.1d-freebsd  10 Sep 2019
ubuntu:19.10: OpenSSL 1.1.1c  28 May 2019
```
Anything older than openssl 1.1.1 does not seem to be affected.

**Comment by manchicken** [comment] 2020-02-23 15:57
Lame. I’ll check with the C lib maintainer. Thanks for the find. 

~ Michael D. Stemle, Jr.

**Comment by manchicken** [comment] 2020-02-29 11:52
Confirmed on CentOS 8. Looking into the dependency.

**Comment by manchicken** [comment] 2020-02-29 12:37
Confirmed broken in dependency. Opened issue https://github.com/alanxz/rabbitmq-c/issues/602

**Comment by manchicken** [comment] 2020-03-05 02:37
I was wrong. This isn't a problem with rabbitmq-c, this is a problem with openssl v1.1.0+ requiring `OPENSSL_CONF` in the environment, and these distros not providing it.

https://github.com/alanxz/rabbitmq-c/issues/602#issuecomment-594987398

**Comment by manchicken** [comment] 2020-03-05 03:44
@eserte I found the root cause of this, but it seems like it may be specific to the distro's config file setup for openssl. I'm thinking that the best thing to do here is to:

1. Add a warning if we detect that the caller's code is affected and needs a missing environment variable.
2. Update the testing setup so that the environment variable is defined when the test matrix is run.

Does this sound like a reasonable approach to you?

**Comment by eserte** [comment] 2020-03-05 07:03
The strace log above shows that `/usr/lib/ssl/openssl.cnf` is loaded, without setting `OPENSSL_CONF`. Anyway, it seems that *loading* the configuration causes the problem --- if I set `OPENSSL_CONF=/etc/ssl` then strace shows that openssl tries to open the file, and fails:
```
12702 06:59:22.025144 openat(AT_FDCWD, "/etc/ssl", O_RDONLY) = 3 <0.000022>
12702 06:59:22.025217 fstat(3, {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0 <0.000022>
12702 06:59:22.025296 read(3, 0x55b5b0206d10, 4096) = -1 EISDIR (Is a directory) <0.000020>
```
One can also set `OPENSSL_CONF=foobar` and the test will pass.

**Comment by manchicken** [comment] 2020-03-05 12:50
That seems like an OpenSSL bug, no?

~ Michael D. Stemle, Jr.

**Comment by manchicken** [comment] 2020-03-05 20:28
@eserte I have this PR: https://github.com/net-amqp-rabbitmq/net-amqp-rabbitmq/pull/187

It adds a warning if you're using openssl v1.1.0+ but don't have that environment variable. I walked through the openssl code and found that the env var is mandatory, or it chokes.

**Comment by manchicken** [comment] 2020-03-06 00:43
Looking through the code, it seemed like it wanted a directory for that. It’s super weird, I’ve got to be missing something. 

I may have to reach out to OpenSSL folks. 

~ Michael D. Stemle, Jr.

**Comment by vdukhovni** [comment] 2020-03-06 03:19
> @eserte I have this PR: #187
> 
> It adds a warning if you're using openssl v1.1.0+ but don't have that environment variable. I walked through the openssl code and found that the env var is mandatory, or it chokes.

This is wrong. OpenSSL DOES NOT require OPENSSL_CONF to be set.  But starting with OpenSSL 1.1.1 the library self-initializes, and loads either the default configuration file or whatever OPENSSL_CONF specifies instead.

The real problem looks like some sort of loop between `/lib/tls/libssl_conf.so`, `/lib/libssl_conf.so` and `/lib/haswell/libssl_conf.so`.  None of these look like they came from OpenSSL, but perhaps they share similar symbols?  What are these objects?  No such libraries appear on my Fedora31 system with `openssl-libs-1.1.1d-2.fc31.x86_64`.

**Comment by manchicken** [comment] 2020-03-06 03:33
If that’s the case then is this distro specific? I’m still trying to figure out whose bug this is. 

~ Michael D. Stemle, Jr.

**Comment by vdukhovni** [comment] 2020-03-06 03:54
> If that’s the case then is this distro specific? I’m still trying to figure out whose bug this is. ~ Michael D. Stemle, Jr.

On the OpenSSL-users list I posed a code snippet for proper initialisation of libssl with a custom application name.  It uses `OPENSSL_init_ssl()` not `CONF_modules_load_file()`.  I don't know why `CONF_modules_load_file()` is looping for the OP, but it is not the preferred way to initialise libssl with OpenSSL 1.1.1.

Not sure whether `CONF_modules_load_file()` is also supposed to work, but I would expect that the underlying built-in "modules" have to already be loaded, and I don't think they would be at that point in the OP's code.  The init code in OpenSSL looks like:
https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/crypto/conf/conf_sap.c#L62-L71
and loads the modules first.

**Comment by Shawak** [comment] 2020-04-29 10:42
Having the same problem. Since https://github.com/alanxz/rabbitmq-c/pull/603 is merged, is there an ETA for a new version on cpan?

**Comment by manchicken** [comment] 2020-04-29 12:56
Sorry, so much work and homeschooling, I haven’t gotten around to updating. I’ll do that tonight. 

~ Michael D. Stemle, Jr.

**Comment by manchicken** [comment] 2020-05-01 03:57
How’s it going? I tidied up quite a bit last night, and it seems like it works with this version now. 

Some of the tests seem to have been affected by network issues. Could we try running them again?

**Comment by eserte** [comment] 2020-05-01 13:06
Net-AMQP-RabbitMQ-2.40007 looks good on my smokers. I think this issue may be closed.

**Comment by manchicken** [comment] 2020-05-01 14:13
Closing. Thanks for your help!

**Closed by manchicken** 2020-05-01 14:13 UTC
