### ISSUE TITLE
Dealing with non-text data?

### ISSUE THREAD

**Issue by eserte** [net-amqp-rabbitmq/net-amqp-rabbitmq#146] opened 2017-01-24 14:04 UTC
Currently `read_message()` makes sure that the body data has the utf8 flag on. These may cause problems especially if the body contains binary or binary-like data.

A possible setup could look like this: a publisher sends json data in the body with `content_type=application/json` and no `content_encoding` (in this case `Net::AMQP::RabbitMQ` translates this to `content_encoding=UTF-8`). The consumer feeds the body data to `JSON::XS::decode_json`. Here it might crash: `JSON::XS::decode_json` expects that it deals with octets, and will die with an "Wide character in subroutine entry" error.

Maybe https://github.com/net-amqp-rabbitmq/net-amqp-rabbitmq/issues/142 is a related problem.

Unfortunately the rabbitmq documentation is quite vague about what `content_encoding` is.
https://www.rabbitmq.com/tutorials/amqp-concepts.html says here "by convention only". Actually, `Content-Encoding` seems to mean in the HTTP world something different — possible values are something like
`compress` and `gzip`, but not `utf-8`. This information would be part of the `Content-Type` header (`text/plain; charset=utf-8`).

So I wonder if `Net::AMQP::RabbitMQ` shouldn't do assume anything about encoding or charset. Or maybe it shouldn't do anything if the `content_type` does not match "`text/*`".

**Comment by pmorch** [comment] 2019-08-08 12:41
I believe this to be a duplicate of #142, and suggest this issue be closed as such and suggest we continue the discussion under #142.

**Comment by manchicken** [comment] 2019-08-08 13:23
Duplicate of #142.

**Closed by manchicken** 2019-08-08 13:23 UTC
