### ISSUE TITLE
t/022_array_headers.t: races between smokers

### ISSUE THREAD

**Issue by eserte** [net-amqp-rabbitmq/net-amqp-rabbitmq#67] opened 2015-09-30 16:31 UTC
See failing t/022_array_headers.t test in sample report http://www.cpantesters.org/cpan/report/11907dc8-676a-11e5-848a-573096b0373b : it looks like two different smokers accessed the same queue or exchange at the same time.

**Comment by markwellis** [comment] 2015-09-30 16:34
this happens all the time, it's because the test suite is designed
terribly, and the tests all rely on the state of the previous test. once
that is fixed we can make $unique have a truly unique number. i have it on
my list for the hackathon on oct 11th

**Comment by markwellis** [comment] 2015-09-30 16:35
sort of a duplicate of #27

**Closed by markwellis** 2015-09-30 16:35 UTC
