### ISSUE TITLE
012_timeout.t fails

### ISSUE THREAD

**Issue by mst2020** [net-amqp-rabbitmq/net-amqp-rabbitmq#196] opened 2020-06-23 15:23 UTC
Hello!

### Error
On Debian/Linux Net-AMQP-RabbitMQ-2.40007 from cpan fails to build because of a wrong test.
```
#   Failed test 'timeout'
#   at t/012_timeout.t line 30.
#     '2.99047'
#         <
#     '0.5'
# Looks like you failed 1 test of 2.
t/012_timeout.t ........................
```

In my opinion the goal of the test is to check if a connection to a non-existing server does not exceed the defined $timeout. (or?)

### Problem
The current implementation:
https://github.com/net-amqp-rabbitmq/net-amqp-rabbitmq/blob/bf99deb79c3bf2507271cdd47cb5fe0fb379cde6/t/012_timeout.t#L26

In my case the two values were:
```
timeout = 3
duration = 0.00953
```
0.00953-3 = -2.99047 = abs() = 2.99047 (& this is not < 0.5)

The connection fails very fast, which is fine and should not result in a wrong test result?

### Solution
I changed the test to:
`cmp_ok($duration, '<', $timeout+0.5, 'timeout');`

Just checking the duration works fine and the goal is the same, but maybe i have overseen something. :)

Greetings and thanks for the good work.

**Comment by manchicken** [comment] 2020-09-30 21:57
@mst2020 Is this still happening?

**Comment by manchicken** [comment] 2020-09-30 22:24
Seems a duplicate of #183

**Comment by mst2020** [comment] 2020-10-01 09:11
> @mst2020 Is this still happening?

Hm ... i don't get it, builds are failing, sometimes - version is "2.40008".

With the same Dockerfile (see below) i have sometimes 10 builds failing and then 10 builds succeed ...
What should/can i do to solve this problem?

```
#   Failed test 'timeout'
#   at t/012_timeout.t line 26.
#     '1.981087'
#         <
#     '0.5'
# Looks like you failed 1 test of 2.
t/012_timeout.t ........................ 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/2 subtests
```
(every other test is "ok")

Here is the Dockerfile i'm using:
```
FROM debian:buster-slim as base
RUN apt-get update -y && apt-get install -y libssl-dev cmake cpanminus
RUN yes | perl -MCPAN -e 'install Net::AMQP::RabbitMQ'
```
Run: `docker build --no-cache .`

My "solution" is to have a local copy with my "fix" and install this version.

**Comment by manchicken** [comment] 2020-10-01 12:10
Always the same test failing?

Also, with that Dockerfile, it seems like you’re installing `cpanm` and then not using it. You may want to try just using `cpanm`. 

~ Michael D. Stemle, Jr.

**Comment by mst2020** [comment] 2020-10-01 12:15
> Always the same test failing?
Yep, always the 12, always the same message.

>Also, with that Dockerfile, it seems like you’re installing `cpanm` and then not using it. You may want to try just using `cpanm`.

Thats because i tested if this might be a problem with cpanm and used it first, but the problem occurs also with the "normal" install. (but you'll see the error messages directly in the output)

**Comment by manchicken** [comment] 2021-10-06 13:33
I just tried this test again in that same Dockerfile and it seems to have been resolved.

I fixed a weird issue involving openssl last year, and I kinda think that might have been the issue. Are you still able to replicate this anywhere?

**Closed** 2022-06-11 02:53 UTC
Labels: Hacktoberfest, investigate
